[package]
name = "string-offsets-js"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "example"

[dependencies]
wasm-bindgen = "0.2"
#rand = "0.8"
#rand_chacha = "0.3"


[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    "-O0"
]